#!/bin/sh
set -e

install_desktop() {
    #for dir in $(find 'config' -not -name 'config' -maxdepth 1);
    for dir in "$PWD"/config/*
    do
        ln -snf "$dir" "$HOME"/.config/"$(basename "$dir")"
        #echo "$dir" "$HOME"/.config/"$(basename "$dir")"
    done
}

install_terminal() {
    for file in .vimrc .bashrc .bash_profile;
    do
        ln -snf "$PWD"/"$file" "$HOME"/"$file"
    done
}

install_windows() {
    cp "$PWD"/config/git/config "$HOME"/.gitconfig
    cp "$PWD"/.bashrc "$HOME"/.bashrc
    cp "$PWD"/.vimrc "$HOME"/.vimrc
    #cp -r "$PWD"/config/nvim
}
