#!/bin/sh
set -e

install_desktop() {
    for src in "$PWD"/config/*;
    do
        file=$(basename "$src")
        dest="$HOME"/.config/"$file"
        ln -snf "$src" "$dest"
    done
}

install_terminal() {
    for file in .vimrc .bashrc .bash_profile;
    do
        ln -snf "$PWD"/"$file" "$HOME"/"$file"
    done
}

install_windows() {
    cp "$PWD"/config/git/config "$HOME"/.gitconfig
    cp "$PWD"/.bashrc "$HOME"/.bashrc
    cp "$PWD"/.vimrc "$HOME"/.vimrc
    #cp -r "$PWD"/config/nvim
}

case $1 in
    desktop) install_desktop;;
    terminal) install_terminal;;
    windows) install_windows;;
esac
