#!/bin/sh

set -e

xdg_config="$HOME"/.config

if [ ! -d "$xdg_config" ]; then
    mkdir -p "$xdg_config"
fi

for n in nvim sway foot waybar fontconfig;
do
    ln -sf "$PWD"/"$n" "$xdg_config"/"$n"
done
