#!/bin/sh

# Check for jq
_have() { type "$1" >/dev/null 2>&1; }
! _have jq && echo 'Requires jq' && exit 1

lookup_fonts() {
  curl -sSL 'https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest' | \
    jq '.assets
      | map(select(.content_type == "application/x-xz")
      | .name |= sub("\\.tar\\.xz"; "") | .name |= ascii_downcase
      | { name: .name, url: .browser_download_url })'
}

list_fonts() {
  lookup_fonts | jq -r '.[].name' && exit 0 || \
    echo 'Unable to look for the fonts' && \
    exit 1
}

download_font() {
  font="$2"
  url="$1"

  install_path="$installation_path/${font}-nerdfont"
  download_path="/tmp/$font.tar.xz"

  curl -sSL "$url" -o "$download_path"
  [ ! -f "$download_path" ] && \
    echo "Could not download the $font" && return 1

  mkdir -p "$install_path"
  tar xJf "$download_path" -C "$install_path" && echo "$font installed in $install_path"
}

search_fonts() {
  input="$1"
  data=$(lookup_fonts)
  for font in $input;
  do
    url=$(echo "$data" | jq -r '.[] | select(.name == "'"$font"'") | .url')
    [ -z "$url" ] && echo "$font not found" && continue
    download_font "$url" "$font"
  done
}

if [ -n "$XDG_DATA_HOME" ]; then
  installation_path="$XDG_DATA_HOME/fonts"
else
  installation_path="$HOME/.fonts"
fi

fonts=""
for arg in "$@"; do
  case "$arg" in
  list) list_fonts;;
  *) fonts="$fonts $arg";;
  esac
done

[ -n "$fonts" ] && search_fonts "$fonts"
